doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        types:
            user_user_id: 'App\Model\User\Entity\User\IdType'
            user_user_email: 'App\Model\User\Entity\User\EmailType'
            user_user_role: 'App\Model\User\Entity\User\RoleType'
            billing_id: 'App\Model\Billing\Entity\Account\IdType'
            billing_member_role: 'App\Model\Billing\Entity\Account\RoleType'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Billing:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Billing/Entity'
                prefix: 'App\Model\Billing\Entity'
                alias: Billing
