services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    App\Tests\Functional\:
        resource: '../tests/Functional/**/*Fixture.php'
        tags: ['doctrine.fixture.orm']
